package com.alexeyosadchy.android.notes.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.alexeyosadchy.android.notes.model.EntityNote;

import com.alexeyosadchy.android.notes.model.EntityNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entityNoteDaoConfig;

    private final EntityNoteDao entityNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entityNoteDaoConfig = daoConfigMap.get(EntityNoteDao.class).clone();
        entityNoteDaoConfig.initIdentityScope(type);

        entityNoteDao = new EntityNoteDao(entityNoteDaoConfig, this);

        registerDao(EntityNote.class, entityNoteDao);
    }
    
    public void clear() {
        entityNoteDaoConfig.clearIdentityScope();
    }

    public EntityNoteDao getEntityNoteDao() {
        return entityNoteDao;
    }

}
